### PR TITLE
added extra functionality

### PR DESCRIPTION
**Pull request by Treggats**
As I mentioned in pull request #2 here is the pull request with the following changes

removed db.sqlite3 and .DS_Store

added the following things
- a list/detail page for the repositories, with a list of issues on the detail page
- a list page for the followers
- a list page for the people one follows
- the github user in the requests is set via the settings file
- added a local_settings import

### CODE REVIEW

**Comment by raybesiga** [comment]
Great job @Treggats. I merged without a problem though I had to create a local_settings file with the following:

```
GITHUB_USER = 'your_github_username'
DEBUG = True
```

I also had change the ALLOWED_HOSTS in the general settings file to:

```
ALLOWED_HOSTS = ['*']
```

We shall need to update the tutorial to reflect these changes. Are you interested in writing Part 2 of the tutorial?

Cheers.

**Comment by Treggats** [comment]
Hi Ray, 

I didn't have to change my allowed_hosts. 
So it's weird you had to. 

Anyway the second part of the tutorial, sounds like fun. Is it an idea to have the tutorial as an wiki page on the repository, or in a doc directory written as a  Markdown file?

**Comment by raybesiga** [comment]
Hey Tonko, 

I think we could make it such that we use the tutorials as the READMEs or we can update the README Markdown file, showing the change of the project over time. Thoughts?

**Comment by Treggats** [comment]
I think that README's should have a short description on what it is, and how to get started.
And not how the code came to be or how it works, internally, That should go in the documentation, or wiki in this case. The tutorial (both parts) can go in there as well.

**Comment by raybesiga** [comment]
So you suggest we add a wiki? @Treggats

**Comment by Treggats** [comment]
I was thinking about this, and readthedocs.org[0] is quite commonly used for documentation. Which would allow us to keep the code and documentation in one repository, instead of separate. The latter is the case when using the GitHub wiki. 

[0] https://read-the-docs.readthedocs.io/en/latest/getting_started.html

**Comment by Treggats** [comment]
Should I come up with a pull request on how this would look?

**Comment by raybesiga** [comment]
Yeah sure.

**Comment by Treggats** [comment]
Hey, so it's a work in progress. But it's a start, I've made a [branch](https://github.com/Treggats/yokogao/commits/convert-readme-to-rtd)  in my fork where I'll work on the tutorials/documentation.

**Comment by raybesiga** [comment]
This is gonna be great @Treggats. Also, I am thinking to create a branch with UI changes. Will keep you posted.

**Pull request merged**
