### PR TITLE
removed .pyc files and fixed the views import in the url conf

### PR DESCRIPTION
**Pull request by Treggats**
I removed the .pyc files from the repository.
When running the code, Django complained about the import in the urls.py
after applying a simple fix everything worked. :)

### CODE REVIEW

**Comment by raybesiga** [comment]
Thank you for this pull request @Treggats. 😄

**Comment by Treggats** [comment]
You're welcome, I followed your tutorial which was nice. But there was no mention of the additional stylesheets. Found them in the git repo, I have made some additional changes. Maybe I'll send a pull request about those changes. 

Cheers

**Comment by raybesiga** [comment]
Yeah, I am thinking to completely rework the stylesheets and maybe add some features to the app. Any ideas?

**Comment by Treggats** [comment]
I'm more a back-end guy, so front-end looks good to me :smile: 
I have added 
- a list/detail page for the repositories, with a list of issues on the detail page
- a list page for the followers
- a list page for the people one follows
- the github user in the requests is set via the settings file
- added a local_settings import

I intent to add a custom context processor, so I can add variables to the base.html. But we'll see how that goes.

**Pull request merged**
